meta_product_name: "Davy-Back-Fight"
meta_title: "Davy-Back-Fight"
meta_description: "Prends part au Davy Back Fight et mises tes berrys sur les questions et mystères de l'univers de One Piece! Qui deviendra le seigneur des pirates?"
meta_image: "banner.png" # should exist in `app/assets/images/`
